/*
Exercise 10: Machine Organization; JavaScript - introduction, syntax, variables, expressions, control structures, and functions 

CMSC 12 | Course

Submitted to:
Professor Aragones

Submitted by:
TEGRADO, Kenneth Renz A.
*/

/*
Tasks:
Write a JavaScript function that takes an array of 8 positive integers as input parameter, and returns an array of integers containing only the numbers that are either: 
    > divisible by 3; OR 
    > even but NOT divisible by 4 
*/

// Start of the main program

// Use Strict Mode
'use strict';

// Init Global Variables
let randomNumberArray = []; // declare an empty array using the array literal
let divisibleNumberArray = []; // declare an empty array using the array literal

// Functions that the program is going to use

// Function to generate an array of eight random numbers
const eightNumberGenerator = (emptyArray) => {
    // accept a parameter of emptyArray
    // Create a sequence of eight random numbers using the for loop then push those numbers to our randomNumberArray
    for (let i = 0; i < 8; i++) {
        // For every iteration of the loop, push the random number generated
        emptyArray.push(Math.trunc(Math.random() * 100) + 1);
        // Use the Math.trunc to round up the values generated by the Math.random()
        // Multiply the value generated of Math.random by 100 to tell what number is our maximum value
        // Add 1 to our value so that we won't get any zero number
    }
};

// Function to generate an array containing all divisiblenumbers
const divisibleNumberGenerator = (randomArray, emptyArray) => {};

// Call our Functions
eightNumberGenerator(randomNumberArray);

// Print our outputs to our console
console.log(randomNumberArray);
